# render.yaml

services:
  - type: web
    name: offline-emergency-chatbot
    env: python
    buildCommand: ""
    startCommand: ./start.sh
    plan: free
    envVars:
      - key: ENV
        value: production
